import React from 'react';
import { TableContainer, Table, TableHead, TableRow, TableCell, TableBody, Paper } from '@material-ui/core';

export default function JcbTable() {
  return (
    <TableContainer component={Paper} style={{maxHeight: 300}}>
      <Table>
        <TableHead>
          <TableRow>
            <TableCell>序号</TableCell>
            <TableCell>通话分钟</TableCell>
            <TableCell>不按时缴费次数</TableCell>
            <TableCell>预期折扣</TableCell>
            <TableCell>预期输出</TableCell>
          </TableRow>
        </TableHead>
        <TableBody>
          <TableRow>
            <TableCell>1</TableCell>
            <TableCell>20</TableCell>
            <TableCell>0</TableCell>
            <TableCell>1.00%</TableCell>
            <TableCell>27.97</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>2</TableCell>
            <TableCell>45</TableCell>
            <TableCell>2</TableCell>
            <TableCell>0.00%</TableCell>
            <TableCell>31.75</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>3</TableCell>
            <TableCell>102</TableCell>
            <TableCell>1</TableCell>
            <TableCell>1.50%</TableCell>
            <TableCell>40.0705</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>4</TableCell>
            <TableCell>113</TableCell>
            <TableCell>3</TableCell>
            <TableCell>0.00%</TableCell>
            <TableCell>41.95</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>5</TableCell>
            <TableCell>156</TableCell>
            <TableCell>2</TableCell>
            <TableCell>2.00%</TableCell>
            <TableCell>47.932</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>6</TableCell>
            <TableCell>164</TableCell>
            <TableCell>4</TableCell>
            <TableCell>0.00%</TableCell>
            <TableCell>49.6</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>7</TableCell>
            <TableCell>213</TableCell>
            <TableCell>2</TableCell>
            <TableCell>2.50%</TableCell>
            <TableCell>56.15125</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>8</TableCell>
            <TableCell>254</TableCell>
            <TableCell>5</TableCell>
            <TableCell>0.00%</TableCell>
            <TableCell>63.1</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>9</TableCell>
            <TableCell>358</TableCell>
            <TableCell>6</TableCell>
            <TableCell>3.00%</TableCell>
            <TableCell>77.089</TableCell>
          </TableRow>
          <TableRow>
            <TableCell>10</TableCell>
            <TableCell>546</TableCell>
            <TableCell>9</TableCell>
            <TableCell>0.00%</TableCell>
            <TableCell>106.9</TableCell>
          </TableRow>
        </TableBody>
      </Table>
    </TableContainer>
  );
}
